window.env = {
  "ALCHEMY_KEY": "https://polygon-mumbai.g.alchemy.com/v2/DeUdi5nWBmawm7YBsvBa0-22aytCHjOk",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "ANDROID_HOME": "E:\\SDK\\SDK",
  "APPDATA": "C:\\Users\\Mufasa\\AppData\\Roaming",
  "APP_BLOCKNATIVE_KEY": "db751b1d-65ea-4f8a-a132-69866bafc679",
  "APP_CHAIN_ID": "80001",
  "APP_CONTACT_EMAIL": "mufasda263129@gmail.com",
  "APP_FORTMATIC_KEY": "pk_live_9F32123A9D83F8DA",
  "APP_INFURA_KEY": "fa8b97680fdd4614b172c724586e8f5b",
  "APP_NAME": "NFT-City",
  "APP_PORTIS_KEY": "42bc626f-e174-4314-939e-bdb358d33930",
  "APP_RPC_URL": "https://rpc-mumbai.maticvigil.com/",
  "APP_URL": "https://map.nft-city.io",
  "COLOR": "1",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-9UAOQLR",
  "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "HOME": "C:\\Users\\Mufasa",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Mufasa",
  "INIT_CWD": "E:\\Alex\\NFTCity",
  "JAVA_HOME": "C:\\Program Files\\Android\\Android Studio\\jre",
  "LOCALAPPDATA": "C:\\Users\\Mufasa\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-9UAOQLR",
  "MAPBPX_ACCESSTOKEN": "pk.eyJ1IjoiYXBldGl0MDExMSIsImEiOiJja3k4Z3NvZTAxZmUxMndxbmJtYWg3MTM2In0.Q3HHmQI-aDwOfi_oTICZJQ",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "start",
  "npm_config_cache": "C:\\Users\\Mufasa\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Mufasa\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Mufasa\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\Mufasa\\.npm-init.js",
  "npm_config_local_prefix": "E:\\Alex\\NFTCity",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Mufasa\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Mufasa\\.npmrc",
  "npm_config_user_agent": "npm/8.5.0 node/v16.14.2 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "start",
  "npm_lifecycle_script": "react-dotenv && craco start",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "E:\\Alex\\NFTCity\\package.json",
  "npm_package_name": "nft-city",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Mufasa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "4",
  "OLD_URL": "http://localhost:8080/",
  "OneDrive": "C:\\Users\\Mufasa\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\Mufasa\\OneDrive",
  "OS": "Windows_NT",
  "Path": "E:\\Alex\\NFTCity\\node_modules\\.bin;E:\\Alex\\node_modules\\.bin;E:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Bitvise SSH Client;D:\\dex-tools-2.1;C:\\Program Files\\Android\\Android Studio\\jre\\bin;E:\\SDK\\SDK\\platform-tools;C:\\Users\\Mufasa\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Mufasa\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Mufasa\\AppData\\Roaming\\npm;C:\\Users\\Mufasa\\AppData\\Local\\GitHubDesktop\\bin",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
  "PINATA_KEY": "3b17a92a4c9dda4d5b35",
  "PINATA_SECRET": "2aa79534fd7847dfcc8887bae753c6848ed6b98bac8c49c5a011acfd9eb92f8c",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 58 Stepping 9, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "3a09",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "REACT_APP_DEFAULT_GATEWAY": "growth.mypinata.cloud",
  "SERVER_URL": "https://xp1v37c0u5.execute-api.us-east-1.amazonaws.com/dev/",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\Mufasa\\AppData\\Local\\Temp",
  "TMP": "C:\\Users\\Mufasa\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-9UAOQLR",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-9UAOQLR",
  "USERNAME": "Mufasa",
  "USERPROFILE": "C:\\Users\\Mufasa",
  "W3W_KEY": "IBB4C9KV",
  "windir": "C:\\WINDOWS"
};